-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_64u_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer13_out_dout : IN STD_LOGIC_VECTOR (1023 downto 0);
    layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    layer13_out_empty_n : IN STD_LOGIC;
    layer13_out_read : OUT STD_LOGIC;
    layer14_out_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    layer14_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_full_n : IN STD_LOGIC;
    layer14_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_64u_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer14_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_idle : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call67 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal data_window_loc_fu_284 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_1_loc_fu_280 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_2_loc_fu_276 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_3_loc_fu_272 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_4_loc_fu_268 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_5_loc_fu_264 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_6_loc_fu_260 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_7_loc_fu_256 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_8_loc_fu_252 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_9_loc_fu_248 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_10_loc_fu_244 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_11_loc_fu_240 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_12_loc_fu_236 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_13_loc_fu_232 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_14_loc_fu_228 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_15_loc_fu_224 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_16_loc_fu_220 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_17_loc_fu_216 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_18_loc_fu_212 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_19_loc_fu_208 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_20_loc_fu_204 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_21_loc_fu_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_22_loc_fu_196 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_23_loc_fu_192 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_24_loc_fu_188 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_25_loc_fu_184 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_26_loc_fu_180 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_27_loc_fu_176 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_28_loc_fu_172 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_29_loc_fu_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_30_loc_fu_164 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_31_loc_fu_160 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_32_loc_fu_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_33_loc_fu_152 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_34_loc_fu_148 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_35_loc_fu_144 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_36_loc_fu_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_37_loc_fu_136 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_38_loc_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_39_loc_fu_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_40_loc_fu_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_41_loc_fu_120 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_42_loc_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_43_loc_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_44_loc_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_45_loc_fu_104 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_46_loc_fu_100 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_47_loc_fu_96 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_48_loc_fu_92 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_49_loc_fu_88 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_50_loc_fu_84 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_51_loc_fu_80 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_52_loc_fu_76 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_53_loc_fu_72 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_54_loc_fu_68 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_55_loc_fu_64 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_56_loc_fu_60 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_57_loc_fu_56 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_58_loc_fu_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_59_loc_fu_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_60_loc_fu_44 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_61_loc_fu_40 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_62_loc_fu_36 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_63_loc_fu_32 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_fu_1197_p129 : STD_LOGIC_VECTOR (1023 downto 0);
    signal layer14_out_write_local : STD_LOGIC;
    signal tmp_65_fu_1187_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_64_fu_1177_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_63_fu_1167_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_62_fu_1157_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_61_fu_1147_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_60_fu_1137_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_59_fu_1127_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_58_fu_1117_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_57_fu_1107_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_56_fu_1097_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_55_fu_1087_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_54_fu_1077_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_53_fu_1067_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_fu_1057_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_51_fu_1047_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_50_fu_1037_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_49_fu_1027_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_48_fu_1017_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_47_fu_1007_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_fu_997_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_45_fu_987_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_44_fu_977_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_967_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_42_fu_957_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_41_fu_947_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_40_fu_937_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_39_fu_927_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_38_fu_917_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_37_fu_907_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_897_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_35_fu_887_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_877_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_867_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_857_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_fu_847_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_fu_837_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_827_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_817_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_fu_807_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_797_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_787_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_777_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_767_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_757_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_747_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_737_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_727_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_717_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_707_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_fu_697_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_687_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_677_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_667_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_657_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_647_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_637_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_627_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_617_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_607_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_597_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_587_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_577_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_567_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_557_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer13_out_dout : IN STD_LOGIC_VECTOR (1023 downto 0);
        layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer13_out_empty_n : IN STD_LOGIC;
        layer13_out_read : OUT STD_LOGIC;
        data_window_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_out_ap_vld : OUT STD_LOGIC;
        data_window_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_1_out_ap_vld : OUT STD_LOGIC;
        data_window_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_2_out_ap_vld : OUT STD_LOGIC;
        data_window_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_3_out_ap_vld : OUT STD_LOGIC;
        data_window_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_4_out_ap_vld : OUT STD_LOGIC;
        data_window_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_5_out_ap_vld : OUT STD_LOGIC;
        data_window_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_6_out_ap_vld : OUT STD_LOGIC;
        data_window_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_7_out_ap_vld : OUT STD_LOGIC;
        data_window_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_8_out_ap_vld : OUT STD_LOGIC;
        data_window_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_9_out_ap_vld : OUT STD_LOGIC;
        data_window_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_10_out_ap_vld : OUT STD_LOGIC;
        data_window_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_11_out_ap_vld : OUT STD_LOGIC;
        data_window_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_12_out_ap_vld : OUT STD_LOGIC;
        data_window_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_13_out_ap_vld : OUT STD_LOGIC;
        data_window_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_14_out_ap_vld : OUT STD_LOGIC;
        data_window_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_15_out_ap_vld : OUT STD_LOGIC;
        data_window_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_16_out_ap_vld : OUT STD_LOGIC;
        data_window_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_17_out_ap_vld : OUT STD_LOGIC;
        data_window_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_18_out_ap_vld : OUT STD_LOGIC;
        data_window_19_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_19_out_ap_vld : OUT STD_LOGIC;
        data_window_20_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_20_out_ap_vld : OUT STD_LOGIC;
        data_window_21_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_21_out_ap_vld : OUT STD_LOGIC;
        data_window_22_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_22_out_ap_vld : OUT STD_LOGIC;
        data_window_23_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_23_out_ap_vld : OUT STD_LOGIC;
        data_window_24_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_24_out_ap_vld : OUT STD_LOGIC;
        data_window_25_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_25_out_ap_vld : OUT STD_LOGIC;
        data_window_26_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_26_out_ap_vld : OUT STD_LOGIC;
        data_window_27_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_27_out_ap_vld : OUT STD_LOGIC;
        data_window_28_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_28_out_ap_vld : OUT STD_LOGIC;
        data_window_29_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_29_out_ap_vld : OUT STD_LOGIC;
        data_window_30_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_30_out_ap_vld : OUT STD_LOGIC;
        data_window_31_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_31_out_ap_vld : OUT STD_LOGIC;
        data_window_32_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_32_out_ap_vld : OUT STD_LOGIC;
        data_window_33_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_33_out_ap_vld : OUT STD_LOGIC;
        data_window_34_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_34_out_ap_vld : OUT STD_LOGIC;
        data_window_35_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_35_out_ap_vld : OUT STD_LOGIC;
        data_window_36_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_36_out_ap_vld : OUT STD_LOGIC;
        data_window_37_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_37_out_ap_vld : OUT STD_LOGIC;
        data_window_38_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_38_out_ap_vld : OUT STD_LOGIC;
        data_window_39_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_39_out_ap_vld : OUT STD_LOGIC;
        data_window_40_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_40_out_ap_vld : OUT STD_LOGIC;
        data_window_41_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_41_out_ap_vld : OUT STD_LOGIC;
        data_window_42_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_42_out_ap_vld : OUT STD_LOGIC;
        data_window_43_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_43_out_ap_vld : OUT STD_LOGIC;
        data_window_44_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_44_out_ap_vld : OUT STD_LOGIC;
        data_window_45_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_45_out_ap_vld : OUT STD_LOGIC;
        data_window_46_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_46_out_ap_vld : OUT STD_LOGIC;
        data_window_47_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_47_out_ap_vld : OUT STD_LOGIC;
        data_window_48_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_48_out_ap_vld : OUT STD_LOGIC;
        data_window_49_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_49_out_ap_vld : OUT STD_LOGIC;
        data_window_50_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_50_out_ap_vld : OUT STD_LOGIC;
        data_window_51_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_51_out_ap_vld : OUT STD_LOGIC;
        data_window_52_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_52_out_ap_vld : OUT STD_LOGIC;
        data_window_53_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_53_out_ap_vld : OUT STD_LOGIC;
        data_window_54_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_54_out_ap_vld : OUT STD_LOGIC;
        data_window_55_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_55_out_ap_vld : OUT STD_LOGIC;
        data_window_56_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_56_out_ap_vld : OUT STD_LOGIC;
        data_window_57_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_57_out_ap_vld : OUT STD_LOGIC;
        data_window_58_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_58_out_ap_vld : OUT STD_LOGIC;
        data_window_59_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_59_out_ap_vld : OUT STD_LOGIC;
        data_window_60_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_60_out_ap_vld : OUT STD_LOGIC;
        data_window_61_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_61_out_ap_vld : OUT STD_LOGIC;
        data_window_62_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_62_out_ap_vld : OUT STD_LOGIC;
        data_window_63_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_63_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295 : component myproject_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start,
        ap_done => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done,
        ap_idle => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_idle,
        ap_ready => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready,
        layer13_out_dout => layer13_out_dout,
        layer13_out_num_data_valid => ap_const_lv9_0,
        layer13_out_fifo_cap => ap_const_lv9_0,
        layer13_out_empty_n => layer13_out_empty_n,
        layer13_out_read => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read,
        data_window_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out,
        data_window_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld,
        data_window_1_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out,
        data_window_1_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld,
        data_window_2_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out,
        data_window_2_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld,
        data_window_3_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out,
        data_window_3_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld,
        data_window_4_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out,
        data_window_4_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld,
        data_window_5_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out,
        data_window_5_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld,
        data_window_6_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out,
        data_window_6_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld,
        data_window_7_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out,
        data_window_7_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld,
        data_window_8_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out,
        data_window_8_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld,
        data_window_9_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out,
        data_window_9_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld,
        data_window_10_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out,
        data_window_10_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld,
        data_window_11_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out,
        data_window_11_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld,
        data_window_12_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out,
        data_window_12_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld,
        data_window_13_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out,
        data_window_13_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld,
        data_window_14_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out,
        data_window_14_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld,
        data_window_15_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out,
        data_window_15_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld,
        data_window_16_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out,
        data_window_16_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld,
        data_window_17_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out,
        data_window_17_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld,
        data_window_18_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out,
        data_window_18_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld,
        data_window_19_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out,
        data_window_19_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld,
        data_window_20_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out,
        data_window_20_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld,
        data_window_21_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out,
        data_window_21_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld,
        data_window_22_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out,
        data_window_22_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld,
        data_window_23_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out,
        data_window_23_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld,
        data_window_24_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out,
        data_window_24_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld,
        data_window_25_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out,
        data_window_25_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld,
        data_window_26_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out,
        data_window_26_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld,
        data_window_27_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out,
        data_window_27_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld,
        data_window_28_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out,
        data_window_28_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld,
        data_window_29_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out,
        data_window_29_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld,
        data_window_30_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out,
        data_window_30_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld,
        data_window_31_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out,
        data_window_31_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld,
        data_window_32_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out,
        data_window_32_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld,
        data_window_33_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out,
        data_window_33_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld,
        data_window_34_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out,
        data_window_34_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld,
        data_window_35_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out,
        data_window_35_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld,
        data_window_36_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out,
        data_window_36_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld,
        data_window_37_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out,
        data_window_37_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld,
        data_window_38_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out,
        data_window_38_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld,
        data_window_39_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out,
        data_window_39_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld,
        data_window_40_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out,
        data_window_40_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld,
        data_window_41_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out,
        data_window_41_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld,
        data_window_42_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out,
        data_window_42_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld,
        data_window_43_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out,
        data_window_43_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld,
        data_window_44_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out,
        data_window_44_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld,
        data_window_45_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out,
        data_window_45_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld,
        data_window_46_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out,
        data_window_46_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld,
        data_window_47_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out,
        data_window_47_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld,
        data_window_48_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out,
        data_window_48_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld,
        data_window_49_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out,
        data_window_49_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld,
        data_window_50_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out,
        data_window_50_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld,
        data_window_51_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out,
        data_window_51_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld,
        data_window_52_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out,
        data_window_52_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld,
        data_window_53_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out,
        data_window_53_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld,
        data_window_54_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out,
        data_window_54_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld,
        data_window_55_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out,
        data_window_55_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld,
        data_window_56_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out,
        data_window_56_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld,
        data_window_57_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out,
        data_window_57_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld,
        data_window_58_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out,
        data_window_58_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld,
        data_window_59_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out,
        data_window_59_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld,
        data_window_60_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out,
        data_window_60_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld,
        data_window_61_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out,
        data_window_61_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld,
        data_window_62_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out,
        data_window_62_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld,
        data_window_63_out => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out,
        data_window_63_out_ap_vld => grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call67) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready = ap_const_logic_1)) then 
                    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_10_loc_fu_244 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_11_loc_fu_240 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_12_loc_fu_236 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_13_loc_fu_232 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_14_loc_fu_228 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_15_loc_fu_224 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld = ap_const_logic_1))) then
                data_window_16_loc_fu_220 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld = ap_const_logic_1))) then
                data_window_17_loc_fu_216 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld = ap_const_logic_1))) then
                data_window_18_loc_fu_212 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld = ap_const_logic_1))) then
                data_window_19_loc_fu_208 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_1_loc_fu_280 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld = ap_const_logic_1))) then
                data_window_20_loc_fu_204 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld = ap_const_logic_1))) then
                data_window_21_loc_fu_200 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld = ap_const_logic_1))) then
                data_window_22_loc_fu_196 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld = ap_const_logic_1))) then
                data_window_23_loc_fu_192 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld = ap_const_logic_1))) then
                data_window_24_loc_fu_188 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld = ap_const_logic_1))) then
                data_window_25_loc_fu_184 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld = ap_const_logic_1))) then
                data_window_26_loc_fu_180 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld = ap_const_logic_1))) then
                data_window_27_loc_fu_176 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld = ap_const_logic_1))) then
                data_window_28_loc_fu_172 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld = ap_const_logic_1))) then
                data_window_29_loc_fu_168 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_2_loc_fu_276 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld = ap_const_logic_1))) then
                data_window_30_loc_fu_164 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld = ap_const_logic_1))) then
                data_window_31_loc_fu_160 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld = ap_const_logic_1))) then
                data_window_32_loc_fu_156 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld = ap_const_logic_1))) then
                data_window_33_loc_fu_152 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld = ap_const_logic_1))) then
                data_window_34_loc_fu_148 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld = ap_const_logic_1))) then
                data_window_35_loc_fu_144 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld = ap_const_logic_1))) then
                data_window_36_loc_fu_140 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld = ap_const_logic_1))) then
                data_window_37_loc_fu_136 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld = ap_const_logic_1))) then
                data_window_38_loc_fu_132 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld = ap_const_logic_1))) then
                data_window_39_loc_fu_128 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_3_loc_fu_272 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld = ap_const_logic_1))) then
                data_window_40_loc_fu_124 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld = ap_const_logic_1))) then
                data_window_41_loc_fu_120 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld = ap_const_logic_1))) then
                data_window_42_loc_fu_116 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld = ap_const_logic_1))) then
                data_window_43_loc_fu_112 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld = ap_const_logic_1))) then
                data_window_44_loc_fu_108 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld = ap_const_logic_1))) then
                data_window_45_loc_fu_104 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld = ap_const_logic_1))) then
                data_window_46_loc_fu_100 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld = ap_const_logic_1))) then
                data_window_47_loc_fu_96 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld = ap_const_logic_1))) then
                data_window_48_loc_fu_92 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld = ap_const_logic_1))) then
                data_window_49_loc_fu_88 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_4_loc_fu_268 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld = ap_const_logic_1))) then
                data_window_50_loc_fu_84 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld = ap_const_logic_1))) then
                data_window_51_loc_fu_80 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld = ap_const_logic_1))) then
                data_window_52_loc_fu_76 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld = ap_const_logic_1))) then
                data_window_53_loc_fu_72 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld = ap_const_logic_1))) then
                data_window_54_loc_fu_68 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld = ap_const_logic_1))) then
                data_window_55_loc_fu_64 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld = ap_const_logic_1))) then
                data_window_56_loc_fu_60 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld = ap_const_logic_1))) then
                data_window_57_loc_fu_56 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld = ap_const_logic_1))) then
                data_window_58_loc_fu_52 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld = ap_const_logic_1))) then
                data_window_59_loc_fu_48 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_5_loc_fu_264 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld = ap_const_logic_1))) then
                data_window_60_loc_fu_44 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld = ap_const_logic_1))) then
                data_window_61_loc_fu_40 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld = ap_const_logic_1))) then
                data_window_62_loc_fu_36 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld = ap_const_logic_1))) then
                data_window_63_loc_fu_32 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_6_loc_fu_260 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_7_loc_fu_256 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_8_loc_fu_252 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_9_loc_fu_248 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_loc_fu_284 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer14_out_full_n, ap_CS_fsm_state3, grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done)
    begin
        if ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(layer14_out_full_n)
    begin
        if ((layer14_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call67_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call67 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer14_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer13_out_read_assign_proc : process(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer13_out_read <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read;
        else 
            layer13_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer14_out_blk_n_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer14_out_blk_n <= layer14_out_full_n;
        else 
            layer14_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer14_out_din <= p_0_fu_1197_p129;
    layer14_out_write <= layer14_out_write_local;

    layer14_out_write_local_assign_proc : process(layer14_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer14_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer14_out_write_local <= ap_const_logic_1;
        else 
            layer14_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_1197_p129 <= (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((tmp_65_fu_1187_p4 & ap_const_lv8_0) & tmp_64_fu_1177_p4) & ap_const_lv8_0) & tmp_63_fu_1167_p4) & ap_const_lv8_0) & tmp_62_fu_1157_p4) & ap_const_lv8_0) & tmp_61_fu_1147_p4) & ap_const_lv8_0) & tmp_60_fu_1137_p4) & ap_const_lv8_0) & tmp_59_fu_1127_p4) & ap_const_lv8_0) & tmp_58_fu_1117_p4) & ap_const_lv8_0) & tmp_57_fu_1107_p4) & ap_const_lv8_0) & tmp_56_fu_1097_p4) & ap_const_lv8_0) & tmp_55_fu_1087_p4) & ap_const_lv8_0) & tmp_54_fu_1077_p4) & ap_const_lv8_0) & tmp_53_fu_1067_p4) & ap_const_lv8_0) & tmp_52_fu_1057_p4) & ap_const_lv8_0) & tmp_51_fu_1047_p4) & ap_const_lv8_0) & tmp_50_fu_1037_p4) & ap_const_lv8_0) & tmp_49_fu_1027_p4) & ap_const_lv8_0) & tmp_48_fu_1017_p4) & ap_const_lv8_0) & tmp_47_fu_1007_p4) & ap_const_lv8_0) & tmp_46_fu_997_p4) & ap_const_lv8_0) & tmp_45_fu_987_p4) & ap_const_lv8_0) & tmp_44_fu_977_p4) & ap_const_lv8_0) & tmp_43_fu_967_p4) & ap_const_lv8_0) & tmp_42_fu_957_p4) 
    & ap_const_lv8_0) & tmp_41_fu_947_p4) & ap_const_lv8_0) & tmp_40_fu_937_p4) & ap_const_lv8_0) & tmp_39_fu_927_p4) & ap_const_lv8_0) & tmp_38_fu_917_p4) & ap_const_lv8_0) & tmp_37_fu_907_p4) & ap_const_lv8_0) & tmp_36_fu_897_p4) & ap_const_lv8_0) & tmp_35_fu_887_p4) & ap_const_lv8_0) & tmp_s_fu_877_p4) & ap_const_lv8_0) & tmp_34_fu_867_p4) & ap_const_lv8_0) & tmp_33_fu_857_p4) & ap_const_lv8_0) & tmp_32_fu_847_p4) & ap_const_lv8_0) & tmp_31_fu_837_p4) & ap_const_lv8_0) & tmp_30_fu_827_p4) & ap_const_lv8_0) & tmp_29_fu_817_p4) & ap_const_lv8_0) & tmp_28_fu_807_p4) & ap_const_lv8_0) & tmp_27_fu_797_p4) & ap_const_lv8_0) & tmp_26_fu_787_p4) & ap_const_lv8_0) & tmp_25_fu_777_p4) & ap_const_lv8_0) & tmp_24_fu_767_p4) & ap_const_lv8_0) & tmp_23_fu_757_p4) & ap_const_lv8_0) & tmp_22_fu_747_p4) & ap_const_lv8_0) & tmp_21_fu_737_p4) & ap_const_lv8_0) & tmp_20_fu_727_p4) & ap_const_lv8_0) & tmp_19_fu_717_p4) & ap_const_lv8_0) & tmp_18_fu_707_p4) & ap_const_lv8_0) & tmp_17_fu_697_p4) & ap_const_lv8_0) & tmp_16_fu_687_p4) 
    & ap_const_lv8_0) & tmp_15_fu_677_p4) & ap_const_lv8_0) & tmp_14_fu_667_p4) & ap_const_lv8_0) & tmp_13_fu_657_p4) & ap_const_lv8_0) & tmp_12_fu_647_p4) & ap_const_lv8_0) & tmp_11_fu_637_p4) & ap_const_lv8_0) & tmp_10_fu_627_p4) & ap_const_lv8_0) & tmp_9_fu_617_p4) & ap_const_lv8_0) & tmp_8_fu_607_p4) & ap_const_lv8_0) & tmp_7_fu_597_p4) & ap_const_lv8_0) & tmp_6_fu_587_p4) & ap_const_lv8_0) & tmp_5_fu_577_p4) & ap_const_lv8_0) & tmp_4_fu_567_p4) & ap_const_lv8_0) & tmp_fu_557_p4) & ap_const_lv8_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_627_p4 <= data_window_7_loc_fu_256(15 downto 8);
    tmp_11_fu_637_p4 <= data_window_8_loc_fu_252(15 downto 8);
    tmp_12_fu_647_p4 <= data_window_9_loc_fu_248(15 downto 8);
    tmp_13_fu_657_p4 <= data_window_10_loc_fu_244(15 downto 8);
    tmp_14_fu_667_p4 <= data_window_11_loc_fu_240(15 downto 8);
    tmp_15_fu_677_p4 <= data_window_12_loc_fu_236(15 downto 8);
    tmp_16_fu_687_p4 <= data_window_13_loc_fu_232(15 downto 8);
    tmp_17_fu_697_p4 <= data_window_14_loc_fu_228(15 downto 8);
    tmp_18_fu_707_p4 <= data_window_15_loc_fu_224(15 downto 8);
    tmp_19_fu_717_p4 <= data_window_16_loc_fu_220(15 downto 8);
    tmp_20_fu_727_p4 <= data_window_17_loc_fu_216(15 downto 8);
    tmp_21_fu_737_p4 <= data_window_18_loc_fu_212(15 downto 8);
    tmp_22_fu_747_p4 <= data_window_19_loc_fu_208(15 downto 8);
    tmp_23_fu_757_p4 <= data_window_20_loc_fu_204(15 downto 8);
    tmp_24_fu_767_p4 <= data_window_21_loc_fu_200(15 downto 8);
    tmp_25_fu_777_p4 <= data_window_22_loc_fu_196(15 downto 8);
    tmp_26_fu_787_p4 <= data_window_23_loc_fu_192(15 downto 8);
    tmp_27_fu_797_p4 <= data_window_24_loc_fu_188(15 downto 8);
    tmp_28_fu_807_p4 <= data_window_25_loc_fu_184(15 downto 8);
    tmp_29_fu_817_p4 <= data_window_26_loc_fu_180(15 downto 8);
    tmp_30_fu_827_p4 <= data_window_27_loc_fu_176(15 downto 8);
    tmp_31_fu_837_p4 <= data_window_28_loc_fu_172(15 downto 8);
    tmp_32_fu_847_p4 <= data_window_29_loc_fu_168(15 downto 8);
    tmp_33_fu_857_p4 <= data_window_30_loc_fu_164(15 downto 8);
    tmp_34_fu_867_p4 <= data_window_31_loc_fu_160(15 downto 8);
    tmp_35_fu_887_p4 <= data_window_33_loc_fu_152(15 downto 8);
    tmp_36_fu_897_p4 <= data_window_34_loc_fu_148(15 downto 8);
    tmp_37_fu_907_p4 <= data_window_35_loc_fu_144(15 downto 8);
    tmp_38_fu_917_p4 <= data_window_36_loc_fu_140(15 downto 8);
    tmp_39_fu_927_p4 <= data_window_37_loc_fu_136(15 downto 8);
    tmp_40_fu_937_p4 <= data_window_38_loc_fu_132(15 downto 8);
    tmp_41_fu_947_p4 <= data_window_39_loc_fu_128(15 downto 8);
    tmp_42_fu_957_p4 <= data_window_40_loc_fu_124(15 downto 8);
    tmp_43_fu_967_p4 <= data_window_41_loc_fu_120(15 downto 8);
    tmp_44_fu_977_p4 <= data_window_42_loc_fu_116(15 downto 8);
    tmp_45_fu_987_p4 <= data_window_43_loc_fu_112(15 downto 8);
    tmp_46_fu_997_p4 <= data_window_44_loc_fu_108(15 downto 8);
    tmp_47_fu_1007_p4 <= data_window_45_loc_fu_104(15 downto 8);
    tmp_48_fu_1017_p4 <= data_window_46_loc_fu_100(15 downto 8);
    tmp_49_fu_1027_p4 <= data_window_47_loc_fu_96(15 downto 8);
    tmp_4_fu_567_p4 <= data_window_1_loc_fu_280(15 downto 8);
    tmp_50_fu_1037_p4 <= data_window_48_loc_fu_92(15 downto 8);
    tmp_51_fu_1047_p4 <= data_window_49_loc_fu_88(15 downto 8);
    tmp_52_fu_1057_p4 <= data_window_50_loc_fu_84(15 downto 8);
    tmp_53_fu_1067_p4 <= data_window_51_loc_fu_80(15 downto 8);
    tmp_54_fu_1077_p4 <= data_window_52_loc_fu_76(15 downto 8);
    tmp_55_fu_1087_p4 <= data_window_53_loc_fu_72(15 downto 8);
    tmp_56_fu_1097_p4 <= data_window_54_loc_fu_68(15 downto 8);
    tmp_57_fu_1107_p4 <= data_window_55_loc_fu_64(15 downto 8);
    tmp_58_fu_1117_p4 <= data_window_56_loc_fu_60(15 downto 8);
    tmp_59_fu_1127_p4 <= data_window_57_loc_fu_56(15 downto 8);
    tmp_5_fu_577_p4 <= data_window_2_loc_fu_276(15 downto 8);
    tmp_60_fu_1137_p4 <= data_window_58_loc_fu_52(15 downto 8);
    tmp_61_fu_1147_p4 <= data_window_59_loc_fu_48(15 downto 8);
    tmp_62_fu_1157_p4 <= data_window_60_loc_fu_44(15 downto 8);
    tmp_63_fu_1167_p4 <= data_window_61_loc_fu_40(15 downto 8);
    tmp_64_fu_1177_p4 <= data_window_62_loc_fu_36(15 downto 8);
    tmp_65_fu_1187_p4 <= data_window_63_loc_fu_32(15 downto 8);
    tmp_6_fu_587_p4 <= data_window_3_loc_fu_272(15 downto 8);
    tmp_7_fu_597_p4 <= data_window_4_loc_fu_268(15 downto 8);
    tmp_8_fu_607_p4 <= data_window_5_loc_fu_264(15 downto 8);
    tmp_9_fu_617_p4 <= data_window_6_loc_fu_260(15 downto 8);
    tmp_fu_557_p4 <= data_window_loc_fu_284(15 downto 8);
    tmp_s_fu_877_p4 <= data_window_32_loc_fu_156(15 downto 8);
end behav;
