// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_64u_config14_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer13_out_dout,
        layer13_out_num_data_valid,
        layer13_out_fifo_cap,
        layer13_out_empty_n,
        layer13_out_read,
        layer14_out_din,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer14_out_full_n,
        layer14_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] layer13_out_dout;
input  [8:0] layer13_out_num_data_valid;
input  [8:0] layer13_out_fifo_cap;
input   layer13_out_empty_n;
output   layer13_out_read;
output  [1023:0] layer14_out_din;
input  [1:0] layer14_out_num_data_valid;
input  [1:0] layer14_out_fifo_cap;
input   layer14_out_full_n;
output   layer14_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer13_out_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer14_out_blk_n;
wire    ap_CS_fsm_state3;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_idle;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld;
wire   [15:0] grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out;
wire    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld;
reg    grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg;
reg    ap_block_state1_ignore_call67;
wire    ap_CS_fsm_state2;
reg   [15:0] data_window_loc_fu_284;
reg   [15:0] data_window_1_loc_fu_280;
reg   [15:0] data_window_2_loc_fu_276;
reg   [15:0] data_window_3_loc_fu_272;
reg   [15:0] data_window_4_loc_fu_268;
reg   [15:0] data_window_5_loc_fu_264;
reg   [15:0] data_window_6_loc_fu_260;
reg   [15:0] data_window_7_loc_fu_256;
reg   [15:0] data_window_8_loc_fu_252;
reg   [15:0] data_window_9_loc_fu_248;
reg   [15:0] data_window_10_loc_fu_244;
reg   [15:0] data_window_11_loc_fu_240;
reg   [15:0] data_window_12_loc_fu_236;
reg   [15:0] data_window_13_loc_fu_232;
reg   [15:0] data_window_14_loc_fu_228;
reg   [15:0] data_window_15_loc_fu_224;
reg   [15:0] data_window_16_loc_fu_220;
reg   [15:0] data_window_17_loc_fu_216;
reg   [15:0] data_window_18_loc_fu_212;
reg   [15:0] data_window_19_loc_fu_208;
reg   [15:0] data_window_20_loc_fu_204;
reg   [15:0] data_window_21_loc_fu_200;
reg   [15:0] data_window_22_loc_fu_196;
reg   [15:0] data_window_23_loc_fu_192;
reg   [15:0] data_window_24_loc_fu_188;
reg   [15:0] data_window_25_loc_fu_184;
reg   [15:0] data_window_26_loc_fu_180;
reg   [15:0] data_window_27_loc_fu_176;
reg   [15:0] data_window_28_loc_fu_172;
reg   [15:0] data_window_29_loc_fu_168;
reg   [15:0] data_window_30_loc_fu_164;
reg   [15:0] data_window_31_loc_fu_160;
reg   [15:0] data_window_32_loc_fu_156;
reg   [15:0] data_window_33_loc_fu_152;
reg   [15:0] data_window_34_loc_fu_148;
reg   [15:0] data_window_35_loc_fu_144;
reg   [15:0] data_window_36_loc_fu_140;
reg   [15:0] data_window_37_loc_fu_136;
reg   [15:0] data_window_38_loc_fu_132;
reg   [15:0] data_window_39_loc_fu_128;
reg   [15:0] data_window_40_loc_fu_124;
reg   [15:0] data_window_41_loc_fu_120;
reg   [15:0] data_window_42_loc_fu_116;
reg   [15:0] data_window_43_loc_fu_112;
reg   [15:0] data_window_44_loc_fu_108;
reg   [15:0] data_window_45_loc_fu_104;
reg   [15:0] data_window_46_loc_fu_100;
reg   [15:0] data_window_47_loc_fu_96;
reg   [15:0] data_window_48_loc_fu_92;
reg   [15:0] data_window_49_loc_fu_88;
reg   [15:0] data_window_50_loc_fu_84;
reg   [15:0] data_window_51_loc_fu_80;
reg   [15:0] data_window_52_loc_fu_76;
reg   [15:0] data_window_53_loc_fu_72;
reg   [15:0] data_window_54_loc_fu_68;
reg   [15:0] data_window_55_loc_fu_64;
reg   [15:0] data_window_56_loc_fu_60;
reg   [15:0] data_window_57_loc_fu_56;
reg   [15:0] data_window_58_loc_fu_52;
reg   [15:0] data_window_59_loc_fu_48;
reg   [15:0] data_window_60_loc_fu_44;
reg   [15:0] data_window_61_loc_fu_40;
reg   [15:0] data_window_62_loc_fu_36;
reg   [15:0] data_window_63_loc_fu_32;
wire   [1023:0] p_0_fu_1197_p129;
reg    layer14_out_write_local;
wire   [7:0] tmp_65_fu_1187_p4;
wire   [7:0] tmp_64_fu_1177_p4;
wire   [7:0] tmp_63_fu_1167_p4;
wire   [7:0] tmp_62_fu_1157_p4;
wire   [7:0] tmp_61_fu_1147_p4;
wire   [7:0] tmp_60_fu_1137_p4;
wire   [7:0] tmp_59_fu_1127_p4;
wire   [7:0] tmp_58_fu_1117_p4;
wire   [7:0] tmp_57_fu_1107_p4;
wire   [7:0] tmp_56_fu_1097_p4;
wire   [7:0] tmp_55_fu_1087_p4;
wire   [7:0] tmp_54_fu_1077_p4;
wire   [7:0] tmp_53_fu_1067_p4;
wire   [7:0] tmp_52_fu_1057_p4;
wire   [7:0] tmp_51_fu_1047_p4;
wire   [7:0] tmp_50_fu_1037_p4;
wire   [7:0] tmp_49_fu_1027_p4;
wire   [7:0] tmp_48_fu_1017_p4;
wire   [7:0] tmp_47_fu_1007_p4;
wire   [7:0] tmp_46_fu_997_p4;
wire   [7:0] tmp_45_fu_987_p4;
wire   [7:0] tmp_44_fu_977_p4;
wire   [7:0] tmp_43_fu_967_p4;
wire   [7:0] tmp_42_fu_957_p4;
wire   [7:0] tmp_41_fu_947_p4;
wire   [7:0] tmp_40_fu_937_p4;
wire   [7:0] tmp_39_fu_927_p4;
wire   [7:0] tmp_38_fu_917_p4;
wire   [7:0] tmp_37_fu_907_p4;
wire   [7:0] tmp_36_fu_897_p4;
wire   [7:0] tmp_35_fu_887_p4;
wire   [7:0] tmp_s_fu_877_p4;
wire   [7:0] tmp_34_fu_867_p4;
wire   [7:0] tmp_33_fu_857_p4;
wire   [7:0] tmp_32_fu_847_p4;
wire   [7:0] tmp_31_fu_837_p4;
wire   [7:0] tmp_30_fu_827_p4;
wire   [7:0] tmp_29_fu_817_p4;
wire   [7:0] tmp_28_fu_807_p4;
wire   [7:0] tmp_27_fu_797_p4;
wire   [7:0] tmp_26_fu_787_p4;
wire   [7:0] tmp_25_fu_777_p4;
wire   [7:0] tmp_24_fu_767_p4;
wire   [7:0] tmp_23_fu_757_p4;
wire   [7:0] tmp_22_fu_747_p4;
wire   [7:0] tmp_21_fu_737_p4;
wire   [7:0] tmp_20_fu_727_p4;
wire   [7:0] tmp_19_fu_717_p4;
wire   [7:0] tmp_18_fu_707_p4;
wire   [7:0] tmp_17_fu_697_p4;
wire   [7:0] tmp_16_fu_687_p4;
wire   [7:0] tmp_15_fu_677_p4;
wire   [7:0] tmp_14_fu_667_p4;
wire   [7:0] tmp_13_fu_657_p4;
wire   [7:0] tmp_12_fu_647_p4;
wire   [7:0] tmp_11_fu_637_p4;
wire   [7:0] tmp_10_fu_627_p4;
wire   [7:0] tmp_9_fu_617_p4;
wire   [7:0] tmp_8_fu_607_p4;
wire   [7:0] tmp_7_fu_597_p4;
wire   [7:0] tmp_6_fu_587_p4;
wire   [7:0] tmp_5_fu_577_p4;
wire   [7:0] tmp_4_fu_567_p4;
wire   [7:0] tmp_fu_557_p4;
reg   [2:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg = 1'b0;
end

myproject_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start),
    .ap_done(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done),
    .ap_idle(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_idle),
    .ap_ready(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(9'd0),
    .layer13_out_fifo_cap(9'd0),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read),
    .data_window_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out),
    .data_window_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld),
    .data_window_1_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out),
    .data_window_1_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld),
    .data_window_2_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out),
    .data_window_2_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld),
    .data_window_3_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out),
    .data_window_3_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld),
    .data_window_4_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out),
    .data_window_4_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld),
    .data_window_5_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out),
    .data_window_5_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld),
    .data_window_6_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out),
    .data_window_6_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld),
    .data_window_7_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out),
    .data_window_7_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld),
    .data_window_8_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out),
    .data_window_8_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld),
    .data_window_9_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out),
    .data_window_9_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld),
    .data_window_10_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out),
    .data_window_10_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld),
    .data_window_11_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out),
    .data_window_11_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld),
    .data_window_12_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out),
    .data_window_12_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld),
    .data_window_13_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out),
    .data_window_13_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld),
    .data_window_14_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out),
    .data_window_14_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld),
    .data_window_15_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out),
    .data_window_15_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld),
    .data_window_16_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out),
    .data_window_16_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld),
    .data_window_17_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out),
    .data_window_17_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld),
    .data_window_18_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out),
    .data_window_18_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld),
    .data_window_19_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out),
    .data_window_19_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld),
    .data_window_20_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out),
    .data_window_20_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld),
    .data_window_21_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out),
    .data_window_21_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld),
    .data_window_22_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out),
    .data_window_22_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld),
    .data_window_23_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out),
    .data_window_23_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld),
    .data_window_24_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out),
    .data_window_24_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld),
    .data_window_25_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out),
    .data_window_25_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld),
    .data_window_26_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out),
    .data_window_26_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld),
    .data_window_27_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out),
    .data_window_27_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld),
    .data_window_28_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out),
    .data_window_28_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld),
    .data_window_29_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out),
    .data_window_29_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld),
    .data_window_30_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out),
    .data_window_30_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld),
    .data_window_31_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out),
    .data_window_31_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld),
    .data_window_32_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out),
    .data_window_32_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld),
    .data_window_33_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out),
    .data_window_33_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld),
    .data_window_34_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out),
    .data_window_34_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld),
    .data_window_35_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out),
    .data_window_35_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld),
    .data_window_36_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out),
    .data_window_36_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld),
    .data_window_37_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out),
    .data_window_37_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld),
    .data_window_38_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out),
    .data_window_38_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld),
    .data_window_39_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out),
    .data_window_39_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld),
    .data_window_40_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out),
    .data_window_40_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld),
    .data_window_41_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out),
    .data_window_41_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld),
    .data_window_42_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out),
    .data_window_42_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld),
    .data_window_43_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out),
    .data_window_43_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld),
    .data_window_44_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out),
    .data_window_44_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld),
    .data_window_45_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out),
    .data_window_45_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld),
    .data_window_46_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out),
    .data_window_46_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld),
    .data_window_47_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out),
    .data_window_47_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld),
    .data_window_48_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out),
    .data_window_48_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld),
    .data_window_49_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out),
    .data_window_49_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld),
    .data_window_50_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out),
    .data_window_50_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld),
    .data_window_51_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out),
    .data_window_51_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld),
    .data_window_52_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out),
    .data_window_52_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld),
    .data_window_53_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out),
    .data_window_53_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld),
    .data_window_54_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out),
    .data_window_54_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld),
    .data_window_55_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out),
    .data_window_55_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld),
    .data_window_56_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out),
    .data_window_56_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld),
    .data_window_57_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out),
    .data_window_57_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld),
    .data_window_58_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out),
    .data_window_58_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld),
    .data_window_59_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out),
    .data_window_59_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld),
    .data_window_60_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out),
    .data_window_60_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld),
    .data_window_61_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out),
    .data_window_61_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld),
    .data_window_62_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out),
    .data_window_62_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld),
    .data_window_63_out(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out),
    .data_window_63_out_ap_vld(grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer14_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call67) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= 1'b1;
        end else if ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_ready == 1'b1)) begin
            grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_10_loc_fu_244 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_11_loc_fu_240 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_12_loc_fu_236 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_12_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_13_loc_fu_232 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_13_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_14_loc_fu_228 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_14_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_15_loc_fu_224 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_15_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out_ap_vld == 1'b1))) begin
        data_window_16_loc_fu_220 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_16_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out_ap_vld == 1'b1))) begin
        data_window_17_loc_fu_216 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_17_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out_ap_vld == 1'b1))) begin
        data_window_18_loc_fu_212 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_18_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out_ap_vld == 1'b1))) begin
        data_window_19_loc_fu_208 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_19_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_1_loc_fu_280 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out_ap_vld == 1'b1))) begin
        data_window_20_loc_fu_204 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_20_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out_ap_vld == 1'b1))) begin
        data_window_21_loc_fu_200 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_21_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out_ap_vld == 1'b1))) begin
        data_window_22_loc_fu_196 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_22_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out_ap_vld == 1'b1))) begin
        data_window_23_loc_fu_192 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_23_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out_ap_vld == 1'b1))) begin
        data_window_24_loc_fu_188 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_24_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out_ap_vld == 1'b1))) begin
        data_window_25_loc_fu_184 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_25_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out_ap_vld == 1'b1))) begin
        data_window_26_loc_fu_180 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_26_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out_ap_vld == 1'b1))) begin
        data_window_27_loc_fu_176 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_27_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out_ap_vld == 1'b1))) begin
        data_window_28_loc_fu_172 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_28_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out_ap_vld == 1'b1))) begin
        data_window_29_loc_fu_168 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_29_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_2_loc_fu_276 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out_ap_vld == 1'b1))) begin
        data_window_30_loc_fu_164 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_30_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out_ap_vld == 1'b1))) begin
        data_window_31_loc_fu_160 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_31_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out_ap_vld == 1'b1))) begin
        data_window_32_loc_fu_156 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_32_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out_ap_vld == 1'b1))) begin
        data_window_33_loc_fu_152 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_33_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out_ap_vld == 1'b1))) begin
        data_window_34_loc_fu_148 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_34_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out_ap_vld == 1'b1))) begin
        data_window_35_loc_fu_144 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_35_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out_ap_vld == 1'b1))) begin
        data_window_36_loc_fu_140 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_36_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out_ap_vld == 1'b1))) begin
        data_window_37_loc_fu_136 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_37_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out_ap_vld == 1'b1))) begin
        data_window_38_loc_fu_132 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_38_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out_ap_vld == 1'b1))) begin
        data_window_39_loc_fu_128 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_39_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_3_loc_fu_272 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out_ap_vld == 1'b1))) begin
        data_window_40_loc_fu_124 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_40_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out_ap_vld == 1'b1))) begin
        data_window_41_loc_fu_120 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_41_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out_ap_vld == 1'b1))) begin
        data_window_42_loc_fu_116 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_42_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out_ap_vld == 1'b1))) begin
        data_window_43_loc_fu_112 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_43_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out_ap_vld == 1'b1))) begin
        data_window_44_loc_fu_108 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_44_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out_ap_vld == 1'b1))) begin
        data_window_45_loc_fu_104 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_45_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out_ap_vld == 1'b1))) begin
        data_window_46_loc_fu_100 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_46_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out_ap_vld == 1'b1))) begin
        data_window_47_loc_fu_96 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_47_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out_ap_vld == 1'b1))) begin
        data_window_48_loc_fu_92 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_48_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out_ap_vld == 1'b1))) begin
        data_window_49_loc_fu_88 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_49_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_4_loc_fu_268 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out_ap_vld == 1'b1))) begin
        data_window_50_loc_fu_84 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_50_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out_ap_vld == 1'b1))) begin
        data_window_51_loc_fu_80 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_51_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out_ap_vld == 1'b1))) begin
        data_window_52_loc_fu_76 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_52_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out_ap_vld == 1'b1))) begin
        data_window_53_loc_fu_72 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_53_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out_ap_vld == 1'b1))) begin
        data_window_54_loc_fu_68 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_54_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out_ap_vld == 1'b1))) begin
        data_window_55_loc_fu_64 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_55_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out_ap_vld == 1'b1))) begin
        data_window_56_loc_fu_60 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_56_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out_ap_vld == 1'b1))) begin
        data_window_57_loc_fu_56 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_57_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out_ap_vld == 1'b1))) begin
        data_window_58_loc_fu_52 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_58_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out_ap_vld == 1'b1))) begin
        data_window_59_loc_fu_48 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_59_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_5_loc_fu_264 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out_ap_vld == 1'b1))) begin
        data_window_60_loc_fu_44 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_60_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out_ap_vld == 1'b1))) begin
        data_window_61_loc_fu_40 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_61_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out_ap_vld == 1'b1))) begin
        data_window_62_loc_fu_36 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_62_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out_ap_vld == 1'b1))) begin
        data_window_63_loc_fu_32 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_63_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_6_loc_fu_260 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_7_loc_fu_256 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_8_loc_fu_252 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_9_loc_fu_248 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_loc_fu_284 <= grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_data_window_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer14_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer14_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer14_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer13_out_read = grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_layer13_out_read;
    end else begin
        layer13_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer14_out_blk_n = layer14_out_full_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer14_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer14_out_write_local = 1'b1;
    end else begin
        layer14_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((layer14_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call67 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start = grp_global_pooling2d_cl_Pipeline_ReadInputHeight_ReadInputWidth_fu_295_ap_start_reg;

assign layer14_out_din = p_0_fu_1197_p129;

assign layer14_out_write = layer14_out_write_local;

assign p_0_fu_1197_p129 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_65_fu_1187_p4}, {8'd0}}, {tmp_64_fu_1177_p4}}, {8'd0}}, {tmp_63_fu_1167_p4}}, {8'd0}}, {tmp_62_fu_1157_p4}}, {8'd0}}, {tmp_61_fu_1147_p4}}, {8'd0}}, {tmp_60_fu_1137_p4}}, {8'd0}}, {tmp_59_fu_1127_p4}}, {8'd0}}, {tmp_58_fu_1117_p4}}, {8'd0}}, {tmp_57_fu_1107_p4}}, {8'd0}}, {tmp_56_fu_1097_p4}}, {8'd0}}, {tmp_55_fu_1087_p4}}, {8'd0}}, {tmp_54_fu_1077_p4}}, {8'd0}}, {tmp_53_fu_1067_p4}}, {8'd0}}, {tmp_52_fu_1057_p4}}, {8'd0}}, {tmp_51_fu_1047_p4}}, {8'd0}}, {tmp_50_fu_1037_p4}}, {8'd0}}, {tmp_49_fu_1027_p4}}, {8'd0}}, {tmp_48_fu_1017_p4}}, {8'd0}}, {tmp_47_fu_1007_p4}}, {8'd0}}, {tmp_46_fu_997_p4}}, {8'd0}}, {tmp_45_fu_987_p4}}, {8'd0}}, {tmp_44_fu_977_p4}}, {8'd0}}, {tmp_43_fu_967_p4}}, {8'd0}}, {tmp_42_fu_957_p4}}, {8'd0}}, {tmp_41_fu_947_p4}}, {8'd0}}, {tmp_40_fu_937_p4}}, {8'd0}}, {tmp_39_fu_927_p4}}, {8'd0}}, {tmp_38_fu_917_p4}}, {8'd0}}, {tmp_37_fu_907_p4}}, {8'd0}}, {tmp_36_fu_897_p4}}, 
    {8'd0}}, {tmp_35_fu_887_p4}}, {8'd0}}, {tmp_s_fu_877_p4}}, {8'd0}}, {tmp_34_fu_867_p4}}, {8'd0}}, {tmp_33_fu_857_p4}}, {8'd0}}, {tmp_32_fu_847_p4}}, {8'd0}}, {tmp_31_fu_837_p4}}, {8'd0}}, {tmp_30_fu_827_p4}}, {8'd0}}, {tmp_29_fu_817_p4}}, {8'd0}}, {tmp_28_fu_807_p4}}, {8'd0}}, {tmp_27_fu_797_p4}}, {8'd0}}, {tmp_26_fu_787_p4}}, {8'd0}}, {tmp_25_fu_777_p4}}, {8'd0}}, {tmp_24_fu_767_p4}}, {8'd0}}, {tmp_23_fu_757_p4}}, {8'd0}}, {tmp_22_fu_747_p4}}, {8'd0}}, {tmp_21_fu_737_p4}}, {8'd0}}, {tmp_20_fu_727_p4}}, {8'd0}}, {tmp_19_fu_717_p4}}, {8'd0}}, {tmp_18_fu_707_p4}}, {8'd0}}, {tmp_17_fu_697_p4}}, {8'd0}}, {tmp_16_fu_687_p4}}, {8'd0}}, {tmp_15_fu_677_p4}}, {8'd0}}, {tmp_14_fu_667_p4}}, {8'd0}}, {tmp_13_fu_657_p4}}, {8'd0}}, {tmp_12_fu_647_p4}}, {8'd0}}, {tmp_11_fu_637_p4}}, {8'd0}}, {tmp_10_fu_627_p4}}, {8'd0}}, {tmp_9_fu_617_p4}}, {8'd0}}, {tmp_8_fu_607_p4}}, {8'd0}}, {tmp_7_fu_597_p4}}, {8'd0}}, {tmp_6_fu_587_p4}}, {8'd0}}, {tmp_5_fu_577_p4}}, {8'd0}}, {tmp_4_fu_567_p4}}, {8'd0}}, {tmp_fu_557_p4}}, {8'd0}};

assign start_out = real_start;

assign tmp_10_fu_627_p4 = {{data_window_7_loc_fu_256[15:8]}};

assign tmp_11_fu_637_p4 = {{data_window_8_loc_fu_252[15:8]}};

assign tmp_12_fu_647_p4 = {{data_window_9_loc_fu_248[15:8]}};

assign tmp_13_fu_657_p4 = {{data_window_10_loc_fu_244[15:8]}};

assign tmp_14_fu_667_p4 = {{data_window_11_loc_fu_240[15:8]}};

assign tmp_15_fu_677_p4 = {{data_window_12_loc_fu_236[15:8]}};

assign tmp_16_fu_687_p4 = {{data_window_13_loc_fu_232[15:8]}};

assign tmp_17_fu_697_p4 = {{data_window_14_loc_fu_228[15:8]}};

assign tmp_18_fu_707_p4 = {{data_window_15_loc_fu_224[15:8]}};

assign tmp_19_fu_717_p4 = {{data_window_16_loc_fu_220[15:8]}};

assign tmp_20_fu_727_p4 = {{data_window_17_loc_fu_216[15:8]}};

assign tmp_21_fu_737_p4 = {{data_window_18_loc_fu_212[15:8]}};

assign tmp_22_fu_747_p4 = {{data_window_19_loc_fu_208[15:8]}};

assign tmp_23_fu_757_p4 = {{data_window_20_loc_fu_204[15:8]}};

assign tmp_24_fu_767_p4 = {{data_window_21_loc_fu_200[15:8]}};

assign tmp_25_fu_777_p4 = {{data_window_22_loc_fu_196[15:8]}};

assign tmp_26_fu_787_p4 = {{data_window_23_loc_fu_192[15:8]}};

assign tmp_27_fu_797_p4 = {{data_window_24_loc_fu_188[15:8]}};

assign tmp_28_fu_807_p4 = {{data_window_25_loc_fu_184[15:8]}};

assign tmp_29_fu_817_p4 = {{data_window_26_loc_fu_180[15:8]}};

assign tmp_30_fu_827_p4 = {{data_window_27_loc_fu_176[15:8]}};

assign tmp_31_fu_837_p4 = {{data_window_28_loc_fu_172[15:8]}};

assign tmp_32_fu_847_p4 = {{data_window_29_loc_fu_168[15:8]}};

assign tmp_33_fu_857_p4 = {{data_window_30_loc_fu_164[15:8]}};

assign tmp_34_fu_867_p4 = {{data_window_31_loc_fu_160[15:8]}};

assign tmp_35_fu_887_p4 = {{data_window_33_loc_fu_152[15:8]}};

assign tmp_36_fu_897_p4 = {{data_window_34_loc_fu_148[15:8]}};

assign tmp_37_fu_907_p4 = {{data_window_35_loc_fu_144[15:8]}};

assign tmp_38_fu_917_p4 = {{data_window_36_loc_fu_140[15:8]}};

assign tmp_39_fu_927_p4 = {{data_window_37_loc_fu_136[15:8]}};

assign tmp_40_fu_937_p4 = {{data_window_38_loc_fu_132[15:8]}};

assign tmp_41_fu_947_p4 = {{data_window_39_loc_fu_128[15:8]}};

assign tmp_42_fu_957_p4 = {{data_window_40_loc_fu_124[15:8]}};

assign tmp_43_fu_967_p4 = {{data_window_41_loc_fu_120[15:8]}};

assign tmp_44_fu_977_p4 = {{data_window_42_loc_fu_116[15:8]}};

assign tmp_45_fu_987_p4 = {{data_window_43_loc_fu_112[15:8]}};

assign tmp_46_fu_997_p4 = {{data_window_44_loc_fu_108[15:8]}};

assign tmp_47_fu_1007_p4 = {{data_window_45_loc_fu_104[15:8]}};

assign tmp_48_fu_1017_p4 = {{data_window_46_loc_fu_100[15:8]}};

assign tmp_49_fu_1027_p4 = {{data_window_47_loc_fu_96[15:8]}};

assign tmp_4_fu_567_p4 = {{data_window_1_loc_fu_280[15:8]}};

assign tmp_50_fu_1037_p4 = {{data_window_48_loc_fu_92[15:8]}};

assign tmp_51_fu_1047_p4 = {{data_window_49_loc_fu_88[15:8]}};

assign tmp_52_fu_1057_p4 = {{data_window_50_loc_fu_84[15:8]}};

assign tmp_53_fu_1067_p4 = {{data_window_51_loc_fu_80[15:8]}};

assign tmp_54_fu_1077_p4 = {{data_window_52_loc_fu_76[15:8]}};

assign tmp_55_fu_1087_p4 = {{data_window_53_loc_fu_72[15:8]}};

assign tmp_56_fu_1097_p4 = {{data_window_54_loc_fu_68[15:8]}};

assign tmp_57_fu_1107_p4 = {{data_window_55_loc_fu_64[15:8]}};

assign tmp_58_fu_1117_p4 = {{data_window_56_loc_fu_60[15:8]}};

assign tmp_59_fu_1127_p4 = {{data_window_57_loc_fu_56[15:8]}};

assign tmp_5_fu_577_p4 = {{data_window_2_loc_fu_276[15:8]}};

assign tmp_60_fu_1137_p4 = {{data_window_58_loc_fu_52[15:8]}};

assign tmp_61_fu_1147_p4 = {{data_window_59_loc_fu_48[15:8]}};

assign tmp_62_fu_1157_p4 = {{data_window_60_loc_fu_44[15:8]}};

assign tmp_63_fu_1167_p4 = {{data_window_61_loc_fu_40[15:8]}};

assign tmp_64_fu_1177_p4 = {{data_window_62_loc_fu_36[15:8]}};

assign tmp_65_fu_1187_p4 = {{data_window_63_loc_fu_32[15:8]}};

assign tmp_6_fu_587_p4 = {{data_window_3_loc_fu_272[15:8]}};

assign tmp_7_fu_597_p4 = {{data_window_4_loc_fu_268[15:8]}};

assign tmp_8_fu_607_p4 = {{data_window_5_loc_fu_264[15:8]}};

assign tmp_9_fu_617_p4 = {{data_window_6_loc_fu_260[15:8]}};

assign tmp_fu_557_p4 = {{data_window_loc_fu_284[15:8]}};

assign tmp_s_fu_877_p4 = {{data_window_32_loc_fu_156[15:8]}};

endmodule //myproject_global_pooling2d_cl_array_array_ap_fixed_16_6_5_3_0_64u_config14_s
